import React from 'react';

interface SitRepProps {
  data: {
    sitrep_id: string | null;
    threat_tier: 'WATCH' | 'ALERT' | 'EMERGENCY';
    status: 'draft' | 'skipped';
    executive_summary: string;
    generated_at: string;
    report?: {
      situation_overview: string;
      epidemiological_analysis: string;
      environmental_context: string;
      risk_assessment: string;
      recommended_actions: string[];
      surveillance_gaps: string[];
      next_review: string;
    };
  };
}

const SitRepViewer: React.FC<SitRepProps> = ({ data }) => {
  // Handle undefined/null data
  if (!data) {
    return null;
  }

  // Don't render if the SitRep was skipped
  if (data.status === 'skipped' || !data.report) {
    return null;
  }

  const { threat_tier, executive_summary, report } = data;
  const isEmergency = threat_tier === 'EMERGENCY';

  return (
    <div className="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden my-6 font-sans">
      {/* WHO-style Header */}
      <div className={`p-4 border-b ${isEmergency ? 'bg-red-50' : 'bg-orange-50'}`}>
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-gray-900 tracking-tight">EWARS Situation Report</h2>
          <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider ${
            isEmergency ? 'bg-red-600 text-white' : 'bg-orange-500 text-white'
          }`}>
            {threat_tier}
          </span>
        </div>
        <div className="flex justify-between items-center mt-2">
          <p className="text-[10px] text-gray-500 font-mono">ID: {data.sitrep_id || 'PENDING'}</p>
          <p className="text-[10px] text-gray-500 font-medium italic">
            Generated: {new Date(data.generated_at).toLocaleString()}
          </p>
        </div>
      </div>

      <div className="p-6 space-y-8">
        {/* Executive Summary Section */}
        <section>
          <h3 className="text-xs font-black text-gray-400 uppercase tracking-[0.2em] mb-3">Section A: Executive Summary</h3>
          <p className="text-gray-800 leading-relaxed font-semibold text-lg border-l-4 border-blue-500 pl-4">
            {executive_summary}
          </p>
        </section>

        {/* Analysis Details */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-6 border-t border-gray-100">
          <section>
            <h4 className="text-sm font-bold text-gray-900 mb-3 underline decoration-blue-200 underline-offset-4">Situation Overview</h4>
            <div className="text-sm text-gray-600 whitespace-pre-wrap leading-relaxed">{report.situation_overview}</div>
          </section>
          <section>
            <h4 className="text-sm font-bold text-gray-900 mb-3 underline decoration-blue-200 underline-offset-4">Epidemiological Analysis</h4>
            <div className="text-sm text-gray-600 whitespace-pre-wrap leading-relaxed">{report.epidemiological_analysis}</div>
          </section>
        </div>

        {/* Actions Section */}
        <section className="bg-gray-50 p-5 rounded-md border border-gray-100">
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <span className="w-2 h-2 bg-gray-800 rounded-full"></span>
            Recommended Actions
          </h4>
          <ul className="space-y-3">
            {report.recommended_actions.map((action, idx) => (
              <li key={idx} className="text-sm text-gray-700 flex gap-3">
                <span className="font-bold text-gray-400">{idx + 1}.</span>
                <span>{action}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* Mandatory Disclaimer */}
        <div className="mt-10 pt-4 border-t border-gray-100">
          <p className="text-[9px] text-gray-400 italic text-center leading-tight max-w-2xl mx-auto">
            This situation report was generated by EWARS (Epidemic Early Warning and Response System), 
            an AI-assisted surveillance tool. It requires review and validation by a qualified 
            epidemiologist before any public health action is taken. All case counts are preliminary 
            and subject to revision. EWARS does not replace human epidemiological judgment.
          </p>
        </div>
      </div>
    </div>
  );
};

export default SitRepViewer;